name: Unittest

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # setup python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip

      # Unit test
      - name: Unit test
        run: python3 -m unittest discover tests
